print("Lưu Minh Hoà đẹp trai khoai to hơn Lê Thanh Huy")
print("Lưu Minh Hoà đẹp trai khoai to hơn Lê Thanh Huy")
print("Lưu Minh Hoà đẹp trai khoai to hơn Lê Thanh Huy")
print("Lưu Minh Hoà đẹp trai khoai to hơn Lê Thanh Huy")
print("Lưu Minh Hoà đẹp trai khoai to hơn Lê Thanh Huy")